### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NicholasJCameron** [c4software/pi-as-keyboard#3]
I have a question for echo -ne "\x00\x00\x00\x17\x00\x00\x00\x00" > /dev/hidg0

I can't map x17 to the letter t... even thought the output is a bunch of t's when I run this script.

Any insight?

**Comment by hemmofa** [comment]
Look on the page numbered 53 & onwards of this PDF for reference to all keys on the keyboard:
http://www.usb.org/developers/hidpage/Hut1_12v2.pdf
I found it after quite a search.

**Comment by c4software** [comment]
Problem solved?

**Comment by NicholasJCameron** [comment]
Yes

**Comment by foxt** [comment]
FUUUUUUUU
![image](https://user-images.githubusercontent.com/12257112/47169978-d7dd5b80-d2fc-11e8-828e-39ab249041d6.png)

**Comment by foxt** [comment]
Never mind, found it on Archive.org
https://web.archive.org/web/20180827225742if_/http://www.usb.org/developers/hidpage/Hut1_12v2.pdf

**Comment by c4software** [comment]
For the record i attach the file here too

[Hut1_12v2.pdf](https://github.com/c4software/pi-as-keyboard/files/2494741/Hut1_12v2.pdf)
