### ISSUE TITLE
Bios Keyboard?

### ISSUE THREAD

**Issue by eafawfawgawg** [c4software/pi-as-keyboard#5]
i've been looking at a auto bios keyboard
tried buying the digispark but couldn't get it to work within the bios. 

Can you confirm if this works within the bios ? / while booting?
appears like the protocol is different when in the bios

Don't wanna go out and buy more stuff if i know it isn't ganna work

**Comment by c4software** [comment]
Hi,

Interesting question, I'm not sure because the Pi need to be up and running to make the action, or maybe you will have to run the Pi, connect to the power off computer and start the computer.

I'm curious what is the exact scenario ?

**Comment by eafawfawgawg** [comment]
removed ^^

**Comment by c4software** [comment]
Hi,

Thanks for the details, i will try something with my computer tomorrow.

Regards

**Comment by eafawfawgawg** [comment]
did you figure it out ^^?

**Comment by c4software** [comment]
I was a bit busy sorry for the delay, I will try it tomorrow.

Again sorry

**Comment by eafawfawgawg** [comment]
That's okay ^^

**Comment by c4software** [comment]
Hi,

Well i have tried in my computer it's working. But i cannot guarantee its will working in any computer… Bios and custom usb keyboard can be tricky !

**Comment by eafawfawgawg** [comment]
well that's promising ^^ guess i'll buy one and try it out then.
Thanks ^^
