### ISSUE TITLE
Possibility to set low speed USB

### ISSUE THREAD

**Issue by burpy** [c4software/pi-as-keyboard#6]
Hi have a RPi Zero keyboard emulation at a franking machine (closed Linux system). Works fine but a cold boot of the franking machine is not possible if the RPi is still connected over USB. I think the machine thinks that there is a USB stick and prevents a boot.

Is there a possibility to set the RPi Zero keyboard emulation to USB low speed? The speed is the only difference that I have to a real keyboard (that works during the booting process).

Thanks!
Jan

**Comment by c4software** [comment]
Hi,

Interesting question, Low Speed like USB1 speed?

**Comment by burpy** [comment]
Right. The real keyboard have 1,5 MBit/s

**Comment by c4software** [comment]
Hi,

Well i have dig the Linux Kernel documentation and some forum its look like its possible, i didn't try by my self. All you have to do is to add this configuration to your /boot/cmdline.txt 

```
dwc_otg.speed=1
```

And reboot. Its should do the tricks

**Comment by burpy** [comment]
I did this and I reboot the Raspberry Zero W but my mac still shows a speed of 480Mb/s instead of 1,5Mb/s. Any more ideas? :)

**Comment by c4software** [comment]
Maybe little late… but did you try to change the line 14 of the file ```enable_hid.sh```

```echo 0x0110 > bcdUSB # USB1.1```
or
```echo 0x0100 > bcdUSB # USB1.0```

**Comment by burpy** [comment]
The bcdUSB makes no difference. But I is not a problem for me anymore because I removed the power USB cable from the raspberry pi zero W and now it starts after the linux computer is started and gets its power over the USB data cable. :)

**Comment by c4software** [comment]
Nice to read ! Problem not fixed but…
