### ISSUE TITLE
enable_hid.service failed

### ISSUE THREAD

**Issue by sevvalmehder** [c4software/pi-as-keyboard#8]
Service failed with this errors after reboot:
raspberrypi systemd[1]: Started Enable HID.
raspberrypi enable_hid.sh[422]: /usr/bin/enable_hid.sh: line 20: configs/c.1/MaxPower: No such file or directory
raspberrypi enable_hid.sh[422]: ln: target 'configs/c.1/' is not a directory: No such file or directory
raspberrypi enable_hid.sh[422]: ls: write error: Device or resource busyt

Then i tried:
systemctl restart enable_hid.service

After this command, again failure with this error:
raspberrypi enable_hid.sh[520]: ls: write error: Device or resource busy

**Comment by c4software** [comment]
Hi,

Thanks for the report, i have made some cleanup recently… and i have made a mistake.

Should be fixed in the latest commit.
